version: "3.8"
services:
  app:
    build: .
    volumes:
      - .:/apps
    ports:
      - 8000:8000
    image: app:apps
    container_name: software_test
    command: python manage.py runserver 0.0.0.0:8000