# Generated by Django 4.0.3 on 2022-03-25 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phonetics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='')),
                ('source_url', models.URLField(blank=True, null=True)),
                ('license', models.CharField(blank=True, max_length=255, null=True)),
                ('license_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('source_url', models.URLField(blank=True, null=True)),
                ('license', models.CharField(blank=True, max_length=255, null=True)),
                ('license_url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
