# Generated by Django 4.0.3 on 2022-03-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('global', 'global'), ('china', 'china'), ('nonChina', 'nonChina')], max_length=255)),
                ('confirmed', models.IntegerField()),
                ('recovered', models.IntegerField()),
                ('death', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Phonetics',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
