# Generated by Django 4.0.3 on 2022-03-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_covid_delete_phonetics_delete_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmed', models.IntegerField(blank=True, null=True)),
                ('recovered', models.IntegerField(blank=True, null=True)),
                ('deaths', models.IntegerField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('sq_km_area', models.IntegerField(blank=True, null=True)),
                ('life_expectancy', models.CharField(blank=True, max_length=255, null=True)),
                ('elevation_in_meters', models.IntegerField(blank=True, null=True)),
                ('continent', models.CharField(blank=True, max_length=255, null=True)),
                ('abbreviation', models.CharField(blank=True, max_length=25, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('capital_city', models.CharField(blank=True, max_length=255, null=True)),
                ('lat', models.IntegerField(blank=True, null=True)),
                ('long', models.IntegerField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Covid',
        ),
    ]
