# Generated by Django 4.0.3 on 2022-03-25 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cases_delete_covid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cases',
            name='lat',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='cases',
            name='long',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
